src/layout/Logo.jsx

First Commit Test

---

src/Main.jsx
src/index.jsx
src/layout/Logo.jsx
src/pages/LandingPage/LandingPage.jsx
src/pages/ListPage/DonationWaitList/DonationList/DonationList.jsx
src/pages/PageNotFound/PageNotFound.css
src/pages/PageNotFound/PageNotFound.jsx

에러 항목 제거, 라우터 기능 추가

---

src/components/Button/Button.jsx
src/hooks/useMediaQuery.js

#추가 사항
- Button 컴포넌트: 추가 prop 지원 기능 추가
- useMediaQuery 커스텀훅: 브레이크 포인트 매직넘버 적용

[최주혁] Fandom-K

---

src/api/donationsApi.js
src/pages/ListPage/DonationWaitList/DonationList/DonationCard.jsx
src/pages/ListPage/DonationWaitList/DonationList/DonationList.jsx

🍎 API 로 DonationList 받아오기 성공

---

src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx

[최주혁] 컨벤션 수정

---

package-lock.json
package.json
src/App.jsx
src/components/Button/Xbutton.jsx
src/components/Modal/Modal.jsx
src/components/TestModals.js/TopupModal.js
src/layout/RootHeader/RootHeader.jsx
src/pages/LandingPage/LandingPage.module.css
src/pages/ListPage/DonationWaitList/DonationWaitList.jsx
src/pages/ListPage/ListPage.jsx
src/pages/ListPage/MyCredit/MyCredit.jsx

- MyCredit 컴포넌트 개발완료
- 후원 목록과 크레딧 공유

[최주혁] MyCredit 컴포넌트 개발

---

src/api/idolsApi.js
src/index.jsx
src/pages/ListPage/MyCredit/MyCredit.jsx

- index.js, idolsApi.js 충돌사항해결
- 사용하지 않는 import 제거

[최주혁] 충돌사항해결

---

public/assets/css/common.css
src/pages/LandingPage/LandingPage.jsx
src/pages/LandingPage/LandingPage.module.css

- 랜딩페이지 스타일 수정
- 스크롤 이벤트 콘솔 제거

[최주혁] 랜딩페이지 스타일 수정

---

src/components/Button/Xbutton.jsx
src/components/TestModalModule.css/Donation.module.css
src/components/TestModalModule.css/Topup.module.css
src/components/TestModalModule.css/Votes.module.css
src/components/TestModals.js/DonationModal.js
src/components/TestModals.js/TopupModal.js
src/components/TestModals.js/VotesModal.js
src/index.jsx

**24.06.18 / 18: 19**
작업 내용 :
1. 투표 모달 디자인 수정
2. 충전 모달 디자인 수정 및 hover 효과 추가
3. Xbutton 컴포넌트 children, className prop 추가
4. 후원 모달 input 내부 스위치 제거

[오조환] 모달 디자인 업데이트

---

package-lock.json
src/components/Modal/Fandom-k_Modal/modal.js/TopupModal.js
src/components/Modal/Modal.jsx
src/pages/ListPage/MyCredit/MyCredit.jsx

24.06.19 /23:19
**작업내용**
- TopupModal 수정

[오조환] TopupModal 수정

---

src/pages/MyPage/MyPage.jsx

[최주혁] MyPage 프롭 수정

---

package-lock.json
package.json
src/components/CaretButton/CaretButton.jsx
src/components/TitleSection/TitleSection.jsx
src/layout/RootHeader/RootHeader.jsx
src/pages/LandingPage/LandingPage.jsx
src/pages/MyPage/AddFavoriteIdols/AddFavoriteIdols.jsx
src/pages/MyPage/AddFavoriteIdols/avatarStyle.css
src/pages/MyPage/MyFavoriteIdols/MyFavoriteIdols.jsx
src/pages/MyPage/MyPage.jsx
src/pages/PageNotFound/PageNotFound.jsx

- MyPage:
- TitleSection 컴포넌트 적용
- Slider 적용
- Prop 명 통일
- RootHeader:
- 각 링크, 현재페이지에 일 때 새로고침 기능 추가

[최주혁] MyPage: TitleSection 컴포넌트 적용

---

public/assets/css/common.css
src/App.jsx
src/components/LodingImage/LodingImage.jsx
src/context/MyCreditContext.jsx
src/layout/RootHeader/RootHeader.jsx
src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx
src/pages/ListPage/ChartOfMonth/ChartOfMonth.module.css
src/pages/ListPage/DonationWaitList/DonationList/CardDecoration.js
src/pages/ListPage/DonationWaitList/DonationList/DonationCard.jsx
src/pages/ListPage/DonationWaitList/DonationWaitList.jsx
src/pages/ListPage/ListPage.jsx
src/pages/ListPage/MyCredit/MyCredit.jsx
src/pages/MyPage/AddFavoriteIdols/AddFavoriteIdols.jsx
src/pages/PageNotFound/PageNotFound.jsx

- 크레딧: 컨텐스트로 구현
- 스켈레톤 UI: 후원리스트, 이달의차트, 아이돌 추가하기 컴포넌트에 적용
- 헤더: 스크롤 반응형 헤더 구현
- 컴포넌트 리로드 시 데이터 초기화 추가

[최주혁] 스켈레톤 UI 구현, 반응형 헤더, 크레딧 컨텍스트

---

src/components/Modal/Fandom-k_Modal/modal.js/DonationModal.js
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Fandom-k_Modal/module.css/Donation.module.css
src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx
src/pages/ListPage/DonationWaitList/DonationWaitList.jsx

24.06.22 / 2:14
**작업내용**
- votes, donation modal components 구조 변경
- donation modal 이미지 링크 수정

[오조환] 모달 구조 변경

---

src/components/Modal/Fandom-k_Modal/modal.js/DonationModal.js
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Fandom-k_Modal/module.css/Donation.module.css
src/components/Modal/Modal.css
src/components/Modal/Modal.jsx
src/hooks/useAsync.js
src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx
src/pages/ListPage/DonationWaitList/DonationList/DonationCard.jsx
src/pages/ListPage/DonationWaitList/DonationWaitList.jsx

24.06.22 / 5:36
**작업내용**
- 모달 업데이트

[오조환] 모달 기능 추가

---

src/components/Avatar/Avatar.jsx
src/context/MyCreditContext.jsx
src/layout/RootHeader/RootHeader.jsx
src/pages/ListPage/MyCredit/MyCredit.jsx
src/pages/MyPage/AddFavoriteIdols/AddFavoriteIdols.jsx
src/pages/MyPage/MyFavoriteIdols/MyFavoriteIdols.jsx

- 캐러셀 UI 개발
- 크레딧 카운트 애니메이션 수정

[최주혁] 캐러셀 UI 개발

---

src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Modal.jsx
src/hooks/useAsync.js
src/pages/ListPage/DonationWaitList/DonationList/DonationCard.jsx
src/pages/ListPage/DonationWaitList/DonationWaitList.jsx

24.06.22 / 9:40
**작업내용**
- 덮어쓰기 파일 수정

[오조환] 덮어쓰기 파일 수정

---

src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx
src/pages/ListPage/ChartOfMonth/ChartOfMonth.module.css

- 더보기 버튼 border 삭제
- 스크롤 문제 해결

더보기 버튼 수정 및 스크롤 문제 해결

---

package-lock.json
package.json
public/assets/css/common.css
src/components/Avatar/Avatar.jsx
src/components/Modal/Fandom-k_Modal/modal.js/TopupModal.js
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Modal.css
src/func/animateFunction.js
src/layout/RootHeader/RootHeader.jsx
src/pages/ListPage/DonationWaitList/DonationWaitList.jsx
src/pages/ListPage/MyCredit/MyCredit.jsx
src/pages/MyPage/AddFavoriteIdols/AddFavoriteIdols.jsx
src/pages/MyPage/MyFavoriteIdols/MyFavoriteIdols.jsx

- 캐러샐 UI 스크롤 애니메이션 기능 모듈화
- 컨벤션 수정

[최주혁] 추가작업

---

package-lock.json
package.json
src/layout/RootHeader/RootHeader.jsx
src/pages/LandingPage/LandingPage.jsx
src/pages/LandingPage/LandingPage.module.css

[최주혁] 랜딩페이지 고도화

---

src/components/CaretButton/CaretButton.jsx
src/components/TitleSection/TitleSection.jsx
src/layout/RootFooter/RootFooter.jsx

- 캐럿버튼 반응형 렌더링 여부
- 구분선 반응형 처리

[최주혁] 마이페이지 반응형 작업

---

src/components/InputRadio/InputRadio.jsx
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Fandom-k_Modal/module.css/Votes.module.css
src/components/Modal/Modal.css
src/components/Modal/Modal.jsx
src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx

24.06.23 / 5:12
**작업내용**
- votes modal 연예인 선택 시 체크 표시 기능 추가

[오조환] 투표 모달 수정

---

src/api/chartsApi.js
src/components/Avatar/Avatar.jsx
src/components/Modal/Fandom-k_Modal/module.css/Votes.module.css
src/components/Modal/Modal.css
src/components/Modal/Modal.jsx

24.06.23 / 8: 17
**작업내용**
- 투표하기 모달 모바일 사이즈 반응형 작업

[오조환] votes 모달 반응형 작업

---

src/api/chartsApi.js
src/api/voteApi.js
src/components/ErrorSection/ErrorSection.jsx
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Fandom-k_Modal/module.css/Votes.module.css
src/components/Modal/Modal.jsx
src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx

[최주혁] 이달의 차트 투표하기 기능 개발

---

src/components/Modal/Fandom-k_Modal/modal.js/DonationModal.js

24.06.24 / 5:14
**작업내용**
- donation modal 잔여 크레딧 애니메이션 추가

[오조환] 후원 모달 애니메이션 추가

---

src/components/ErrorSection/ErrorSection.jsx
src/components/Modal/Fandom-k_Modal/modal.js/DonationModal.js
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/components/Modal/Fandom-k_Modal/module.css/Votes.module.css

24.06.24 / 11:05
**작업내용**
- votes modal 랭크 오표시 오류 해결

[오조환] 투표 모달 랭크 오류 수정

---

1
src/components/ErrorSection/ErrorSection.jsx
src/layout/RootHeader/MoemaButton.jsx
src/layout/RootHeader/RootHeader.jsx

[윤수현] 반응형 수정

---

src/api/voteApi.js
src/components/Modal/Fandom-k_Modal/modal.js/VotesModal.js
src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx
src/pages/MyPage/AddFavoriteIdols/AddFavoriteIdols.jsx

- 이달의 차트: 차트투표 이후 순위 사라지는 버그 수정
- 로그 출력 제거

[최주혁] 이달의 차트 버그 수정

---

src/pages/ListPage/ChartOfMonth/ChartOfMonth.jsx

[최주혁] 배포 버전 업데이트
